### ISSUE TITLE
Make the request faster, now it is nearly a second

### ISSUE THREAD

**Issue by jakublaz** [piolad/chat-app#37]

**Comment by piotr-ladkowski** [comment]
seems to be a problem on auth-service side

**Comment by piotr-ladkowski** [comment]
id recommedn going over docker networks

**Comment by piotr-ladkowski** [comment]
| 12:35:49.926 info: Login request received from brud
auth-service-1            | 2024-05-27 12:35:50.129785095 UTC: login request started
auth-service-1            | 2024-05-27 12:35:50.150877393 UTC: after query
auth-service-1            | 2024-05-27 12:35:50.151056616 UTC: before password verification
auth-service-1            | 2024-05-27 12:35:53.714706542 UTC: verification ok

**Comment by piotr-ladkowski** [comment]
seems like password verification takes a long time

**Comment by piotr-ladkowski** [comment]
btw this branch will not be merged, will be deleted instead

**Comment by jakublaz** [comment]
On my branch i have found the solution to the problem, by default the hashing cost, so the complexity was at 10. Knocking it down to 4 lowers the hashing time but also lowers security
