### ISSUE TITLE
[browser-facade] Sender/Receiver make the display correct

### ISSUE THREAD

**Issue by piotr-ladkowski** [piolad/chat-app#56]
Currently conversation Sender and Receiver are determined by who messaged first. Thus, if `Kuba` messages `brud` first, the Receiver for both of them will be `brud`, no matter who is logged in.

Fix this and make it so the conversation is displayed nicely.

See `browser-facade/aspnetapp/Pages/Friends.cshtml` and `browser-facade/aspnetapp/Pages/Friends.cshtml.cs`.

**Comment by jakublaz** [comment]
It is ready on my branch, will be uploaded with the next bigger pull request

**Comment by piotr-ladkowski** [comment]
Seems ok from 1 glance.
Maybe there is no need for bigger PR, we can push it as a quick fix if you want
